# Generated by Django 2.0.6 on 2018-06-15 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docportal', '0002_auto_20180615_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docportal.ManufacturedUnitModel')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='manufacturedunitmodel',
            name='viewer',
            field=models.ManyToManyField(through='docportal.UnitPermission', to=settings.AUTH_USER_MODEL),
        ),
    ]
