# Generated by Django 2.0.6 on 2018-06-15 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docportal', '0003_auto_20180615_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturedunitmodel',
            old_name='viewer',
            new_name='viewers',
        ),
    ]
