# Generated by Django 2.0.6 on 2018-06-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docportal', '0004_auto_20180615_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmodel',
            name='file',
            field=models.FileField(null=True, upload_to='docs'),
        ),
    ]
